services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      RATE_LIMIT_CAPACITY: "5"
      RATE_LIMIT_REFILL_RATE: "1"
      ADMISSION_MAX_QUEUE_LENGTH: "500"
    deploy:
      replicas: 1 # Change for more replicas

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api