# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

# @name bookEvent
POST http://127.0.0.1:8000/events/1/book
Accept: application/json
Content-Type: application/json

{
  "user_id": "user-1"
}

> {%
    client.global.set("reservation_id", response.body.reservation_id);
%}

###

GET http://127.0.0.1:8000/reservations/{{reservation_id}}
Accept: application/json

###
